all:
	gcc -w -o main main.c
	gcc -w -o p1 p1.c
	gcc -w -o p2 p2.c
	gcc -w -o p3 p3.c
	gcc -w -o p4 p4.c
	gcc -w -o p5 p5.c
	gcc -w -o p6 p6.c

clean:
	rm -f main
	rm -f p1
	rm -f p2
	rm -f p3
	rm -f p4
	rm -f p5
	rm -f p6
